# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_route',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
