# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_app', '0007_game_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('ninja_pref', models.CharField(max_length=255)),
                ('monk_pref', models.CharField(max_length=255)),
                ('no_act', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='DnD_app.Character')),
            ],
        ),
    ]
