# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_app', '0008_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='character',
        ),
    ]
