# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_app', '0009_remove_story_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='strength',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
